CREATE DATABASE q_store ENCODING 'utf8';
CREATE USER quarkus ENCRYPTED PASSWORD 'quarkus';
GRANT ALL PRIVILEGES ON DATABASE q_store TO quarkus WITH GRANT OPTION;
ALTER DATABASE q_store OWNER TO quarkus;