# datasource configuration
quarkus:
  application:
    name: "Quarkus Store API"
  http:
    port: 8082
    read-timeout: 30m
    enable-compression: true
  package:
    type: uber-jar
  datasource:
    db-kind: postgresql
    username: quarkus
    password: quarkus
    jdbc:
      url: "jdbc:postgresql://localhost:5432/q_store"
  hibernate-orm:
    database:
      generation: drop-and-create
    packages: foo.bar.store.model
    sql-load-script: import.sql
  oidc:
    enabled: true
    auth-server-url: "http://localhost:8180/realms/qstore"
    "client-id": "qstore-api"
    credentials:
      secret: "qstore"
    tls:
      verification: none
    token:
      issuer: any
    "application-type": "service"
  log:
    level: DEBUG
    min-level: TRACE
    category:
      "org.jboss":
        level: WARN
      "org.hibernate":
        level: INFO
      "io.quarkus":
        level: WARN
      "io.quarkiverse":
        level: DEBUG
      "io.smallrye":
        level: WARN
      "org.eclipse":
        level: WARN
      "io.netty":
        level: WARN
      "foo.bar.store":
        level: TRACE
    console:
      enable: true
      level: DEBUG
    file:
      level: DEBUG
      enable: true
      path: "log/quarkus-store-api.log"
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      rotation:
        max-backup-index: 5
        max-file-size: 10M
  swagger-ui:
    always-include: true

"%test":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        url: "jdbc:h2:file:./target/data/database;AUTO_SERVER=true;DB_CLOSE_DELAY=-1"
    hibernate-orm:
      dialect: org.hibernate.dialect.H2Dialect
      log:
        sql: true

"%prod":
  quarkus:
    hibernate-orm:
      sql-load-script: no-file