version: '3.5'
services:
  postgresql:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: "on-failure"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    command: [
      "start-dev --hostname-strict=false"
    ]
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"

